version: '3.8'

services:
  parcel-app:
    image: piyush1146115/parcel:latest
    container_name: parcel-container
    network_mode: host
    ports:
      - "8090:8090"
    restart: on-failure

  redis:
    image: redis:7-alpine
    container_name: my-redis-container
    network_mode: host
    ports:
      - "6379:6379"
    restart: on-failure
